In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter

In [2]:
data = pd.read_csv('Kinematics_Data.csv')

In [3]:
from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score, precision_score, f1_score
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

import lightgbm as lgb

In [4]:
data

,date,time,username,wrist,activity,acceleration_x,acceleration_y,acceleration_z,gyro_x,gyro_y,gyro_z
0,2017-6-30,13:51:15:847724020,viktor,0,0,0.2650,-0.7814,-0.0076,-0.0590,0.0325,-2.9296
1,2017-6-30,13:51:16:246945023,viktor,0,0,0.6722,-1.1233,-0.2344,-0.1757,0.0208,0.1269
2,2017-6-30,13:51:16:446233987,viktor,0,0,0.4399,-1.4817,0.0722,-0.9105,0.1063,-2.4367
3,2017-6-30,13:51:16:646117985,viktor,0,0,0.3031,-0.8125,0.0888,0.1199,-0.4099,-2.9336
4,2017-6-30,13:51:16:846738994,viktor,0,0,0.4814,-0.9312,0.0359,0.0527,0.4379,2.4922
...,...,...,...,...,...,...,...,...,...,...,...
88583,2017-7-9,20:9:15:317911028,viktor,0,0,0.3084,-0.8376,-0.1327,0.4823,2.0124,0.6048
88584,2017-7-9,20:9:15:517889022,viktor,0,0,0.4977,-1.0027,-0.4397,0.1022,-1.2565,-0.0761
88585,2017-7-9,20:9:15:717828989,viktor,0,0,0.4587,-1.1780,-0.2827,-1.4500,-0.2792,-1.2616
88586,2017-7-9,20:9:15:917932987,viktor,0,0,0.2590,-0.8582,-0.0759,-1.5165,0.4560,-1.7755
88587,2017-7-9,20:9:16:117410004,viktor,0,0,0.3140,-0.8008,-0.0911,0.1183,1.0850,1.2814

In [5]:
X = data.iloc[:, 5:]

In [6]:
Y1 = data['wrist']
Y2 = data['activity']

In [7]:
train_x1, test_x1, train_y1, test_y1 = train_test_split(X, Y1, test_size = 0.3, stratify=Y1, random_state = 2022)

In [8]:
train_x2, test_x2, train_y2, test_y2 = train_test_split(X, Y2, test_size = 0.3, stratify=Y2, random_state = 2022)

In [9]:
#성능 평가
def model_evaluation(true, pred):
    print('Confusion Matrix')
    print(confution_matrix(true, pred, labels=[1,0]))
    print()
    print(f'Accuracy : {accuracy_score(true, pred)}')
    print(f'Recall : {recall_score(true, pred, pos_label=1)}')
    print(f'precision : {precision_score(true, pred, pos_label=1)}')
    print(f'F1 : {f1_score(true, pred, pos_label=1)}')